### ISSUE TITLE
Issue with uint16 zarr data

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-io#107]
There seems to be an issue with uint16 zarr data. 
It throws the following error:
```
java.lang.ClassCastException: net.imglib2.img.basictypeaccess.volatiles.array.VolatileDoubleArray cannot be cast to net.imglib2.img.basictypeaccess.ShortAccess

	at net.imglib2.type.numeric.integer.GenericShortType.updateContainer(GenericShortType.java:104)
	at net.imglib2.img.cell.CellRandomAccess.updatePosition(CellRandomAccess.java:487)
	at net.imglib2.img.cell.CellRandomAccess.<init>(CellRandomAccess.java:136)
	at net.imglib2.img.cell.AbstractCellImg.randomAccess(AbstractCellImg.java:104)
	at net.imglib2.img.cell.AbstractCellImg.randomAccess(AbstractCellImg.java:51)
	at net.imglib2.util.Util.getTypeFromInterval(Util.java:806)
	at net.imglib2.view.Views.iterable(Views.java:777)
```
Some example data is here: `/g/kreshuk/pape/Work/playground/mobie-projects/spatial-trans/test.ome.zarr`.
(Note that the datatype encoding is a bit weird in zarr, it's written as `<u2`; `<`: little endian, `u`: unsigned, `2`: 2 bytes; but the error message seems to show that it does at leat get that it's a short datatype).

**Comment by tischi** [comment]
Yes, I don't get it either yet. I also asked here: https://gitter.im/bigdataviewer/bigdataviewer-core

**Comment by KateMoreva** [comment]
> but the error message seems to show that it does at leat get that it's a short datatype).

No, from debugging it seems that we read it as a VolatileDoubleArray. I missed that the data should be uint16, checking this might solve the problem.

**Comment by constantinpape** [comment]
> No, from debugging it seems that we read it as a VolatileDoubleArray. I missed that the data should be uint16, checking this might solve the problem.

For some context: the dtype encoding follows the numpy standard and is further explained here: https://zarr.readthedocs.io/en/stable/spec/v2.html#data-type-encoding

**Comment by tischi** [comment]
I think there is some wrong type annotation in the file:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/2157566/181000412-e3539e2f-21ec-4a7b-923a-fc7ccb1bf478.png">

**Comment by tischi** [comment]
Yes, the different resolution pyramids have different types:

```
tischer@mac-almf13 axon-ring-3d-tracing (main) $ cat /Volumes/kreshuk/pape/Work/playground/mobie-projects/spatial-trans/test.ome.zarr/0/.zarray 
{
    "chunks": [
        6,
        64,
        64
    ],
    "compressor": {
        "id": "zlib",
        "level": 5
    },
    "dtype": "<u2",
    "fill_value": 0.0,
    "filters": null,
    "order": "C",
    "shape": [
        6,
        2048,
        2048
    ],
    "zarr_format": 2
}
tischer@mac-almf13 axon-ring-3d-tracing (main) $ cat /Volumes/kreshuk/pape/Work/playground/mobie-projects/spatial-trans/test.ome.zarr/4/.zarray 
{
    "chunks": [
        6,
        64,
        64
    ],
    "compressor": {
        "id": "zlib",
        "level": 5
    },
    "dtype": "<f8",
    "fill_value": 0.0,
    "filters": null,
    "order": "C",
    "shape": [
        6,
        128,
        128
    ],
    "zarr_format": 2
}

```

**Comment by constantinpape** [comment]
Ok, probably some downsampling issue. I will double check and see that I fix it.
Will ping you then.

**Comment by constantinpape** [comment]
Yes, that fixes the issue. This is most likely caused by a bug in `ome-zarr-py` when writing the data. I will see if I can reproduce it and follow up with an issue there.

**Comment by constantinpape** [comment]
This is the culprit: https://github.com/ome/ome-zarr-py/issues/217
