### ISSUE TITLE
Test data CXY

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#108]
@constantinpape 

Could you please add some S3 test data (or point me to it) with dimensions like this:

```
 "axes": [
                {
                    "name": "c",
                    "type": "channel"
                },
                {
                    "name": "y",
                    "type": "space",
                    "unit": "micrometer"
                },
                {
                    "name": "x",
                    "type": "space",
                    "unit": "micrometer"
                }
```

@tibuch data is like that and our code (in `multi-channel-fix`) does open it as a multi-channel image, but each channel has a wrong z-dimension (is: 4, should be: 1) that is equal to the number of channels. 

And I checked, the code in `develop` is even worse, it only detects the channel axis as a z-axis.

I would thus suggest we keep working on the `multi-channel-fix` branch.

Who should try to fix this, should I do it or someone else fancy for it?

**Comment by constantinpape** [comment]
@tischi you can find all the example data in https://s3.embl.de/i2k-2020/ngff-example-data/v0.4/.
In this case https://s3.embl.de/i2k-2020/ngff-example-data/v0.4/cyx.ome.zarr is what you're looking for.

**Comment by tischi** [comment]
@KateMoreva do you have a sense of where the error could be?

**Comment by constantinpape** [comment]
> @KateMoreva do you have a sense of where the error could be?

What exactly is the error?

**Comment by tischi** [comment]
> each channel has a wrong z-dimension that is equal to the number of channels.

I am looking into it....

**Comment by tischi** [comment]
I added several questions (marked with TODO) to the multi-channel-fix branch where I don't understand the current code. I would have some time tomorrow morning to have a look together at it.

**Comment by KateMoreva** [comment]
> And I checked, the code in develop is even worse, it only detects the channel axis as a z-axis.

I'll check it out.
But I don't think we missed this bug for so long.

**Comment by tischi** [comment]
@KateMoreva 
Please don't change anything, let's do this together!
I feel we need to change a lot in the current code. 
Do you have time tomorrow morning?

**Comment by KateMoreva** [comment]
@tischi 
Yes, when is it convenient for you?

**Comment by constantinpape** [comment]
The ngff tests are now all here: https://github.com/mobie/mobie-io/tree/develop/src/test/java/projects/ngff including the one for CYX
