### ISSUE TITLE
AxisOrder

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#11]
@KateMoreva (@constantinpape)

The code currently contains a lot of boolean variables: `is2D`, ...

Could you please have a look whether we could get rid of them and replace them by an `enum` such as `bdv.util.AxisOrder`?

**Comment by constantinpape** [comment]
So would you expect something like this?: (pseudocode)
```
axes_values = enum{ZYX, YX, CYX, ...}

if axes == axes_values.ZYX:
   # do stuff for zyx
elif axes == axes_values.YX
   # do stuff for yx
```

**Comment by tischi** [comment]
Yes, and the point would be that the enum [exists already](https://github.com/bigdataviewer/bigdataviewer-vistools/blob/5c2b94b833f238f0fa506997bffa68a5406e6b93/src/main/java/bdv/util/AxisOrder.java#L46) in the BDV ecosystem.

**Comment by constantinpape** [comment]
> Yes, and the point would be that the enum [exists already](https://github.com/bigdataviewer/bigdataviewer-vistools/blob/5c2b94b833f238f0fa506997bffa68a5406e6b93/src/main/java/bdv/util/AxisOrder.java#L46) in the BDV ecosystem.

Ok, I see. I agree that we should use it, although it's a bit unfortunate that the axis conventions are different....

**Comment by tischi** [comment]
> although it's a bit unfortunate that the axis conventions are different

different in which sense?

**Comment by constantinpape** [comment]
Reversed:
| ome.zarr | bdv |
| ------------ | ---- |
| yx            | xy  |
| zyx          | xyz |
| cyx          | xyc |
etc

**Comment by tischi** [comment]
If necessary, we could create an `OMEZARRAxisOrder` enum and write code such as `toAxisOrder( OMEZARRAxisOrder ozao )` and `toOMEZARRAxisOrder( AxisOrder ao )`.

But I am not sure it is necessary, maybe @KateMoreva could look into the code to see whether we need the `OMEZARRAxisOrder` at all...

**Comment by KateMoreva** [comment]
If there are problems with axes reverting now they might be useful. For now, we can use an extra method and `axesMap` if needed.

**Comment by constantinpape** [comment]
We have checked this often now and the data is loaded in the correct axis order.
