### ISSUE TITLE
github API rate limit exceeded

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#111]
@constantinpape @KateMoreva 

I am getting an error:

```
java.lang.RuntimeException
Unexpected response code: 403
null.
403 rate limit exceeded
X-RateLimit-Resource: core
Server: Varnish
X-RateLimit-Used: 60
Access-Control-Allow-Origin: *
X-Content-Type-Options: nosniff
X-RateLimit-Reset: 1659546239
Date: Wed, 03 Aug 2022 16:38:04 GMT
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
X-Frame-Options: deny
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-RateLimit-Remaining: 0
X-GitHub-Media-Type: github.v3; format=json
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'
X-RateLimit-Limit: 60
Content-Length: 280
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C975:4125:1DADD49:1E8E678:62EAA46C
Content-Type: application/json; charset=utf-8
```

<img width="869" alt="image" src="https://user-images.githubusercontent.com/2157566/182662147-4f2130b1-fc0d-42f1-afef-505b782d6dc1.png">

This seems to have something to do with sending too many requests to the GitHub REST API. I don't know if they changed their policy or why that happens now. 

Hmm, I see that trying the same operation in the `default` branch of `mobie-viewer-fiji` works. So probably some changes/bug that I introduced in the `mobie3` branch of `mobie-viewer-fiji`.

Anyway I think it would be good to better understand what exactly that error message means and how we exactly are causing it.

If you know anything about this let me know.

**Comment by constantinpape** [comment]
Indeed it looks like exceeding the number of API requests.
For more details: https://docs.github.com/en/developers/apps/building-github-apps/rate-limits-for-github-apps
http://coderdiaries.com/github-error-rate-limit-exceeded/

**Comment by tischi** [comment]
Yes, however, there must be also a per-second or per-minute limit which I have hit. 
Would be good to know the number.

The reason was that I initialized not only the table content (which we load without the API) but also the loadable table paths, for which we need to inspect the table directory content using the GitHub API. As I do this multi-threaded quite some requests (for `covid-if`) are generated in parallel. We don't really need to know this information initially, so I could simply remove this. 

However good to know the using the GitHub API for multi-threaded requests is not an option!
