### ISSUE TITLE
Cannot finish release....

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#127]
@imagejan @nicokiaru @ctrueden

I don't manage to consistently get rid of this error:

```
[main 7de1efd] Bump to next development cycle
 2 files changed, 20 insertions(+), 1 deletion(-)
 create mode 100644 release.properties
error: Your local changes to the following files would be overwritten by checkout:
        release.properties
Please commit your changes or stash them before you switch branches.
Aborting
```

Sometimes deleting the `release.properties` file helped, but now it doesn't....

Any ideas? Thanks a lot!

**Comment by tischi** [comment]
I tried to rerun: `../scijava-scripts/github-actionify.sh -f`
I think it did something, but then in the end it gave:`fatal: pathspec '.travis.yml' did not match any files`
Which seems a bit weird because I don't see any `.travis.yml` file...
Anyway, it did not help regarding the above error.

**Comment by tischi** [comment]
I found that now there is only one script: `build.yml`, while there used to be two in older versions of `github-actionify.sh`?

Anyway, also this did not fix the issue:

```
error: Your local changes to the following files would be overwritten by checkout:
        release.properties
```

Probably something simple and stupid, but I cannot figure it out right now...

**Comment by NicoKiaru** [comment]
Currently you have test errors in [your build](https://github.com/mobie/mobie-io/actions/runs/3126593382/jobs/5072267547):

```
	  java.lang.NoClassDefFoundError: Could not initialize class org.janelia.saalfeldlab.n5.blosc.BloscCompression
  	at dataformats.ngff.v01.YXNgffV01Test.<init>(YXNgffV01Test.java:40)
```

But you're speaking of a different issue ?

**Comment by ctrueden** [comment]
@tischi The `release.properties` file should not be committed to source control on the main/master branch. If you accidentally committed it, do another commit that deletes it before trying to do a release.

**Comment by ctrueden** [comment]
I added logic to `release-version.sh` to [clean up `release.properties` and `pom.xml.releaseBackup`](https://github.com/scijava/scijava-scripts/commit/00b78cbe0dd4aecf612bdb78bfa5c0598e83c8e6) so they are less likely to get committed to the main repository branch.

**Comment by tischi** [comment]
@NicoKiaru Thanks for spotting this, we need `sudo apt-get install -y libblosc1` in the setup.sh script. I added this back.

@ctrueden Thank you, but it still is not working. I always delete `release.properties` and commit the delete before running `../scijava-scripts/release-version.sh --skip-version-check`

```
[main 1f7ddfb] Bump to next development cycle
 3 files changed, 239 insertions(+), 1 deletion(-)
 create mode 100644 pom.xml.releaseBackup
 create mode 100644 release.properties
error: Your local changes to the following files would be overwritten by checkout:
        release.properties
Please commit your changes or stash them before you switch branches.
Aborting
tischer@mac-almf13 mobie-io (main) $ ls -la
total 56
drwxr-xr-x   13 tischer  staff   416B Sep 26 16:27 ./
drwx------+ 300 tischer  staff   9.4K Sep 23 10:47 ../
drwxr-xr-x   15 tischer  staff   480B Sep 26 16:27 .git/
drwxr-xr-x    5 tischer  staff   160B Sep 26 16:22 .github/
-rw-r--r--    1 tischer  staff   158B Aug  3  2021 .gitignore
drwxr-xr-x    9 tischer  staff   288B Sep 26 16:22 .idea/
-rw-r--r--    1 tischer  staff   1.3K Sep 26 16:25 LICENSE.txt
-rw-r--r--    1 tischer  staff   1.3K Sep 26 11:13 README.md
-rw-r--r--    1 tischer  staff   1.3K Sep 23 14:02 genereate_ngff_version_tests.py
-rw-r--r--    1 tischer  staff    67B Sep 23 14:02 log4j.properties
-rw-r--r--    1 tischer  staff   7.5K Sep 26 16:27 pom.xml
drwxr-xr-x    4 tischer  staff   128B Aug  3  2021 src/
drwxr-xr-x   16 tischer  staff   512B Sep 26 16:27 target/
```

Any more ideas?

**Comment by tischi** [comment]
> Could it be that this log4j.properties file is the culprit?

No, removing that does not fix it.

**Comment by ctrueden** [comment]
@tischi Weird, it looks like your autogenerated "Bump to next development cycle" commits are readding the `release.properties` and `pom.xml.releaseBackup` for some reason. Investigating now. (It takes me awhile to test, because this repo's unit tests are very slow, and I also have to work around not having push access.)

> `../scijava-scripts/release-version.sh --skip-version-check`

Why are you passing `--skip-version-check`? This check is important, and should only be skipped as needed. E.g. when a new pom-scijava is freshly released, the index is out of date, and the check detects the wrong version as newest, so you can skip it in that situation, but in general, you want to be updating your parent POM version to the latest pom-scijava whenever one is available. You also want to check that you are performing a valid version bump according to SemVer.

**Comment by constantinpape** [comment]
@tischi:

> Thank you, but it still is not working. I always delete `release.properties` and commit the delete before running `../scijava-scripts/release-version.sh --skip-version-check`

Are you sure that deleting `release.properties` has worked (also in git)?

Because  `error: Your local changes to the following files would be overwritten by checkout: release.properties`
only makes sense if this file is still somehow in git.

Can you paste the output of `git status` here?

**Comment by tischi** [comment]
> The only thing I can think of, which is a long-shot, is that you have something in your `.gitconfig` to automatically add untracked files when doing `git commit`?

@ctrueden you nailed it :rocket:! Turns out my IntelliJ was doing exactly that. Switching that off fixed it! Thank you so much for taking the time to dig into this :heart:
