### ISSUE TITLE
Merge main and develop

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#128]
@constantinpape

I recently updated the `main` branch to be compatible with the latest fiji. 
When locally trying to merge `main` into `develop` there were many changes in the tests that you wrote.
I am confused about what is happening...and I don't want to screw up.
Could you also try merging `main` into `develop`?

I am asking now, because before we merge this: https://github.com/mobie/mobie-io/pull/121
I thought it would be better to update the `develop` branch before.

**Comment by constantinpape** [comment]
Ok, I will check it out.

**Comment by constantinpape** [comment]
> When locally trying to merge `main` into `develop` there were many changes in the tests that you wrote.
> I am confused about what is happening...and I don't want to screw up.

I checked it out, these are just the license header that have been added by the release script and no real code changes. I have merged main into dev now (https://github.com/mobie/mobie-io/pull/129). I think https://github.com/mobie/mobie-io/pull/121 is good to go now.
