### ISSUE TITLE
Mobie-IO beta update didn't work

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-io#130]
Hey @tischi,
unfortunately your mobie-beta update didn't work. Are you sure you pushed the latest version from develop to it?

For reference, on the left you see "https://s3.embl.de/i2k-2020/ngff-example-data/v0.4/image-with-labels.ome.zarr" opened with mobie-io from `develop` via https://github.com/mobie/mobie-io/blob/develop/src/test/java/ui/OmeZarrS3V4Opener.java#L88-L91 on the right you see it opened with the latest mobie-beta and `BDV->OME-Zarr S3`

![image](https://user-images.githubusercontent.com/4263537/194032197-027ba01e-28f9-4e92-a093-89f3544275f8.png)

**Comment by tischi** [comment]
If you go to your Fiji jars folder, does it look like this?

<img width="559" alt="image" src="https://user-images.githubusercontent.com/2157566/194033590-68ce530a-3139-47de-b7b7-0ad4324e956a.png">

**Comment by tischi** [comment]
There is another issue. The OME-Zarr viewer in MoBIE currently does a lot of stuff, where I am not sure this is working. I will change it to simply do what we do in mobie-io...

**Comment by tischi** [comment]
ok, please update (in the new Fiji, it seems you have to actually ask it to do this, it does not automatically do that anymore).

**Comment by constantinpape** [comment]
Yes, it's working now. Thanks!
