### ISSUE TITLE
Table header is not browseable

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#133]
This does not work: https://mobie.github.io/specs/mobie_spec.html#tables

**Comment by constantinpape** [comment]
This cannot work, since the corresponding section is called `Table Data`, so the link is https://mobie.github.io/specs/mobie_spec.html#table-data (and works).

**Comment by tischi** [comment]
Then it is wrong here: 

> See the [table data specification](https://mobie.github.io/specs/mobie_spec.html#tables) for details on how tables are stored.

**Comment by constantinpape** [comment]
> Then it is wrong here:
> 
> > See the [table data specification](https://mobie.github.io/specs/mobie_spec.html#tables) for details on how tables are stored.

Yes, where exactly is this from?

**Comment by tischi** [comment]
From the mobie-io website.

**Comment by constantinpape** [comment]
> From the mobie-io website.

I am not sue what you mean by `mobie-io` website. Do you mean https://mobie.github.io/ ? These are two quite different things ...

**Comment by tischi** [comment]
yes: https://mobie.github.io/
The text above is copied from there.

**Comment by constantinpape** [comment]
I have fixed the links now. (If you find broken links again, can you please make an issue in https://github.com/mobie/mobie.github.io. I was pretty confused by the issue being here.)
