### ISSUE TITLE
bigdataviewer-image-loaders dependency

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#137]
@NicoKiaru I may want to have    as a dependency of `mobie-io`.

Do you know whether I have to upload all those dependencies to the MoBIE update site or could I omit some of them?

```
		<dependency>
			<groupId>com.zeroc</groupId>
			<artifactId>glacier2</artifactId>
			<version>${glacier2.version}</version>
		</dependency>
		<dependency>
			<groupId>com.zeroc</groupId>
			<artifactId>ice</artifactId>
			<version>${ice.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openmicroscopy</groupId>
			<artifactId>ome-xml</artifactId>
		</dependency>
		<dependency>
			<groupId>org.openmicroscopy</groupId>
			<artifactId>omero-blitz</artifactId>
			<version>${omero-blitz.version}</version>
			<exclusions>
				<exclusion>  <!-- declare the exclusion here -->
					<groupId>net.sourceforge.findbugs</groupId>
					<artifactId>annotations</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.openmicroscopy</groupId>
			<artifactId>omero-gateway</artifactId>
			<version>${omero-gateway.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openmicroscopy</groupId>
			<artifactId>omero-model</artifactId>
		</dependency>
```

**Comment by tischi** [comment]
What we gain from this is that we can open anything that is supported by Bio-Formats as SpimData.

```
    public AbstractSpimData< ? > openSpimData(String imagePath, ImageDataFormat imageDataFormat) throws UnsupportedOperationException, SpimDataException {
        switch (imageDataFormat) {
            case BioFormats:
                return openWithBioFormats(imagePath);
```

**Comment by NicoKiaru** [comment]
Hi tischi, 

Normally you just need to add bigdataviewer-image-loaders (v0.4.3 on the 15th Feb 2023) dependency. The rest comes with transitive dependencies.

> Do you know whether I have to upload all those dependencies to the MoBIE update site or could I omit some of them?

So you should be able to omit all of them. 
Which version did you try ?

HOWEVER, nothing works currently on the update sites. I have several repos to migrate at the same time on the PTBIOP update site. My target for the 'big update' is in two weeks.

Right now you can test and see if everything works ok in the IDE, but then we need to synchronize the Fiji release.

Side note: you can open any bio-formats supported file, as well as dataset from OMERO, and also QuPath projects. All lazy loaded, with multi-resolution support and with 8 bits unsigned, 16 bits unsigned, float and rgb pixel type support.

**Comment by tischi** [comment]
I know that those are transitive dependencies, but I think I still have to upload them to the MoBIE update site.

And I think if @tinenvez wants to use `mobie-io` in Mastodon then I think he also would have to add them to their update site. 

If I only upload `bigdataviewer-image-loader` we are getting within Fiji, e.g.:

`Caused by: java.lang.NoClassDefFoundError: omero/model/enums/UnitsLength
    at ch.epfl.biop.bdv.img.opener.OpenerSettings.<init>(OpenerSettings.java:78)`

**Comment by tischi** [comment]
version `0.4.0`

**Comment by NicoKiaru** [comment]
Yes, so this issue is fixed is 0.4.3

**Comment by NicoKiaru** [comment]
Now if you activate the OMERO-5.5-5.6 update site this should be ok as well

**Comment by NicoKiaru** [comment]
With 0.4.3: no need to have the OMERO update site enabled if you stick to Bio-Formats.

**Comment by NicoKiaru** [comment]
Damned, there's a stupid bug in 0.4.3 regarding the units. Will fix in 0.4.4

**Comment by tischi** [comment]
Meanwhile I can confirm that from `0.4.3` on one only needs to ship `bigdataviewer-image-loaders` on the update site. And maybe, if one does not use the Bio-Formats features of mobie-io one does not even need to ship that...

**Comment by NicoKiaru** [comment]
Ok, the 0.4.4 arrives in 2 minutes

**Comment by tischi** [comment]
@tinevez I _think_ with those changes 

1. Just uploading `mobie-io` _without_ any new additional dependencies should work for you.
2. If you also want to open Bio-Formats file formats as SpimData, just additionally uploading `bigdataviewer-image-loaders` should do the job.
