### ISSUE TITLE
Move OME-Zarr opening to MoBIE plugin tree

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#139]
@d-v-d
@joshmoore
@constantinpape 
@bogovicj

I feel I would like to move 

`Plugins › BigDataViewer › OME-Zarr › Open OME-Zarr From S3...`
`Plugins › BigDataViewer › OME-Zarr › Open OME-Zarr From File System...`
`Plugins › BigDataViewer › OME-Zarr › Open OME-Zarr From S3 with Credentials...`

to

`Plugins › MoBIE › OME-Zarr › Open OME-Zarr From S3...`
a.s.o.

because OME-Zarr Java support is still under discussion and development and I am not sure whether what we currently do in mobie-io will be the default mechanism in the future.

Would you be fine with this?

**Comment by joshmoore** [comment]
> Would you be fine with this?

Yes, but I don't really have a horse in the race. Will macros, etc. break?

**Comment by tischi** [comment]
> Will macros, etc. break?

I don't think so as macro calls are not recording the full path but only the last bit, which would not change.

**Comment by constantinpape** [comment]
I don't have a strong opinion here.

**Comment by tischi** [comment]
I moved it to within MoBIE.
