### ISSUE TITLE
lombock dependency

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#141]
Do we really need this?

It is only used for class annotations:

import lombok.extern.slf4j.Slf4j;

```
@Slf4j
public class N5CacheArrayLoader<A> implements SimpleCacheArrayLoader<A> {
    private final N5Reader n5;
    private final String pathName;
    private final DatasetAttributes attributes;
    private final Function<DataBlock<?>, A> createArray;
```

----

```
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
            <scope>compile</scope>
        </dependency>
```

**Comment by tischi** [comment]
@KateMoreva @constantinpape @joshmoore do you know where those `@Slf4j` annotations come from. I checked quickly in the upstream N5 repositories and could not find them there....

**Comment by KateMoreva** [comment]
I added this annotation in order to change logging (but haven't had time to add it everyware), can remove it if you wish.

**Comment by tischi** [comment]
I think it would be good to remove it; less dependencies is always better.
Could you please remove it?

**Comment by KateMoreva** [comment]
Ok

**Comment by KateMoreva** [comment]
> lombock is now removed in `develop`

@tischi why did you choose to use System.out.println instead of logging with proper logger (wich is configurable and much useful)? I thought the idea was to just get rid of projectlombok not logger.?

**Comment by tischi** [comment]
@KateMoreva 
Sorry, I just wanted to fix it in some way that was easy and reduced the number of dependencies. 
I may have overdone it....
