### ISSUE TITLE
Implement getFileList for AWS S3

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#153]
@constantinpape for https://github.com/mobie/mobie-viewer-fiji/issues/1076 I think we will need an implementation for [getFileList](https://github.com/mobie/mobie-io/blob/1fe0c15fadf93c0ba953fa9e882e62ec111e6b1d/src/main/java/org/embl/mobie/io/util/IOHelper.java#L103) for AWS S3. Otherwise we cannot know which wells and channels there are and thus cannot produce the plate.

do you agree?

chatGPT suggests:

```
  Yes, you can get a list of objects in an S3 folder by using the AWS SDK for Java and specifying a delimiter (such as
  "/") when listing the objects. Here's an example using the AWS SDK for Java 2.x:

    S3Client s3 = S3Client.builder().build();
    ListObjectsV2Request listReq = ListObjectsV2Request.builder()
            .bucket("my-bucket-name")
            .prefix("my-folder/")
            .delimiter("/")
            .build();
    ListObjectsV2Response listRes = s3.listObjectsV2(listReq);

    for (S3Object content : listRes.contents()) {
        System.out.println("Key: " + content.key());
    }

  Replace  "my-bucket-name"  with your bucket name and  "my-folder/"  with the folder path in the bucket. The delimiter
  "/" will ensure that you get a listing of objects contained within that folder.
```

Do you have the S3 address for your Incuyte data such that we can test this?

**Comment by constantinpape** [comment]
> @constantinpape for [mobie/mobie-viewer-fiji#1076](https://github.com/mobie/mobie-viewer-fiji/issues/1076) I think we will need an implementation for [getFileList](https://github.com/mobie/mobie-io/blob/1fe0c15fadf93c0ba953fa9e882e62ec111e6b1d/src/main/java/org/embl/mobie/io/util/IOHelper.java#L103) for AWS S3. Otherwise we cannot know which wells and channels there are and thus cannot produce the plate.
> 
> do you agree?

For our use-case this would not strictly be necessary. We would know this beforehand from metadata and could produce a table that is read by MoBIE to tell it where the respective folders are. (And this is also something that would help with performance, because the list operations on s3 are slow, especially since we would have a big archive and it would otherwise need to list a lot of folders).

But in general I think it's still useful to have this.

> Do you have the S3 address for your Incuyte data such that we can test this?

Please see https://github.com/mobie/mobie-viewer-fiji/issues/1075#issue-2040343500.

**Comment by tischi** [comment]
I found that we already have:

```
public static ArrayList<String> getS3FilePaths(String directory) {
        final AmazonS3 s3 = getS3Client(directory);
        final String[] bucketAndObject = getBucketAndObject(directory);

        final String bucket = bucketAndObject[0];
        final String prefix = bucketAndObject[ 1 ].isEmpty() ? "" : ( bucketAndObject[1] + "/" );
        
        ListObjectsV2Request request = new ListObjectsV2Request()
            .withBucketName(bucket)
            .withPrefix(prefix)
            .withDelimiter("/");
        ListObjectsV2Result files = s3.listObjectsV2(request);
        final ArrayList<String> paths = new ArrayList<>();
        for (S3ObjectSummary summary : files.getObjectSummaries()) {
            paths.add(summary.getKey());
        }
        return paths;
    }
```

But it does not seem to work as expected; I don't get the list. There are other ways of doing this, but it seems we are using a very old version of the AWS library. I don't think I can easily update this as this comes as a transitive dependency of N5.

**Comment by tischi** [comment]
This works:

```
        S3Objects.withPrefix( s3, bucket, prefix ).forEach( (S3ObjectSummary objectSummary ) -> {
            String path = IOHelper.combinePath( directory, objectSummary.getKey().replace( prefix, "" ) );
            paths.add( path );
        });
```
