### ISSUE TITLE
bdv vs bdv.hdf5

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#155]
@constantinpape @martinschorb do you remember what the difference between those two ImageDataFormats 
 is supposed to be?

```
    @SerializedName(BDV)
    Bdv,
    @SerializedName(BDVHDF5)
    BdvHDF5,
```

**Comment by constantinpape** [comment]
No I don't recall. I don't think `BDV` on its own makes sense. Maybe it was some synonym for another BDV datatype?
