### ISSUE TITLE
Support of BDV XML/N5 on S3 needed?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#156]
@constantinpape @martinschorb @jhennies,

Do you know whether there are still projects that use BDV XML/N5 on S3 ?

If not, I would consider deprecating our support for this (unless this is supported upstream by bdv or n5 libraries).

**Comment by constantinpape** [comment]
Yes, the majority of our projects are still saved in BDV XML.N5 and also use it for S3.

**Comment by martinschorb** [comment]
Same here. Most Volume EM projects are on BDV-N5 (Render exports this and they are still implementing OME-Zarr support).

**Comment by jhennies** [comment]
Also the same here. Nothing much to add but BDV-N5 is still alive

**Comment by tischi** [comment]
@martinschorb could you please give me the location of such an XML?

**Comment by tischi** [comment]
found one:

https://github.com/mobie/platybrowser-project/blob/main/data/1.0.1/images/remote/sbem-6dpf-1-whole-raw.xml

**Comment by tischi** [comment]
However, pasting any of those in the browser tells me "key does not exist"....

`https://s3.embl.de/platybrowser/rawdata/sbem-6dpf-1-whole-raw.n5/`
`https://s3.embl.de/platybrowser/rawdata/sbem-6dpf-1-whole-raw.n5/.zgroup`
`https://s3.embl.de/platybrowser/rawdata/sbem-6dpf-1-whole-raw.n5/.zattrs`

**Comment by tischi** [comment]
Also:

```
❯ aws s3 ls s3://embl.de/platybrowser/rawdata/sbem-6dpf-1-whole-raw.n5 --no-sign-request

An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
```

**Comment by martinschorb** [comment]
https://s3.embl.de/platybrowser/rawdata/sbem-6dpf-1-whole-raw.xml works for me.

**Comment by jhennies** [comment]
This one works for me and has n5 data on s3: https://github.com/mobie/environmental-dinoflagellate-vCLEM

I'm currently on mobie-viewer-fiji-4.2.3.jar

**Comment by tischi** [comment]
I figured out how to further support this.
