### ISSUE TITLE
Support only OME-Zarr for writing

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#161]
I would suggest to from now on to only support OME-Zarr for writing image data from within MoBIE in Fiji.

Is that OK?

@constantinpape @martinschorb @jhennies

**Comment by jhennies** [comment]
To make sure I can follow: You mean when you create a mobie project in Fiji, only ome.zarr can be written. That would be fine with me

**Comment by martinschorb** [comment]
good from my side as well

**Comment by tischi** [comment]
Thanks!
