### ISSUE TITLE
Default axis for ilastik hdf5 (exported from Fiji)

### ISSUE THREAD

**Issue by k-dominik** [mobie/mobie-io#163]
Dear @tischi,

the [ilastik Fiji plugin](https://github.com/ilastik/ilastik4ij?tab=readme-ov-file#ilastik-imagej-modules) ungracefully doesn't save axistags to the dataset. However, the axisorder is always fixed `tzyxc`.

Would it be possible to add a default to MoBiE, for loading these files?

Example file: 
[export.zip](https://github.com/mobie/mobie-io/files/14605491/export.zip)

**Comment by tischi** [comment]
Thanks, I will work on it this afternoon.

Related, are there any ways to determine from the h5 file (i) the desired contrast limits and (ii) the desired rendering color?

**Comment by k-dominik** [comment]
No, we don't save those at all :/ What do you think would be a reasonable way to do that? Adding some kind of metadata tag to the file and adhering to the ome spec?

Side note, it would be cool if we could look at this https://github.com/ilastik/ilastik4ij/blob/661310c92c54280218f8af5e849f1539e629e65a/src/main/java/org/ilastik/ilastik4ij/hdf5/Hdf5.java#L230 together to also write the axistags on ours side. My java-fu is a bit rusty  ;)

**Comment by tischi** [comment]
Works now, I also needed to add:

```
            final N5HDF5Reader n5 = new N5HDF5Reader( uri );
            String dataset = "exported_data";
            if ( ! n5.datasetExists( dataset ) )
                dataset = "data";
```

**Comment by k-dominik** [comment]
Hey @tischi, thank you so much for fixing this. In principle the dataset name can be any string, but let's record for now, that only the default strings "data" and "exported_data" are supported.

**Comment by tischi** [comment]
Hey @k-dominik, could you please

1. test whether that now also works in Fiji
2. inform the user on the forum upon success

Thanks!

**Comment by k-dominik** [comment]
Hi @tischi,

I gave it a go and it doesn't really seem to work:

<img width="981" alt="image" src="https://github.com/mobie/mobie-io/assets/24434157/d84fd426-c9d3-4983-a364-09aed58e341e">

this should be the famous "blobs" image.

Could the axisorder be maybe the other way round? (`cxyzt`)

**Comment by tischi** [comment]
Hard to say...

<img width="424" alt="image" src="https://github.com/mobie/mobie-io/assets/2157566/11839f21-9e5f-4322-bf64-5568ff969cb3">


Could you create an example that also has a z-dimension?

**Comment by tischi** [comment]
Got it:

<img width="912" alt="image" src="https://github.com/mobie/mobie-io/assets/2157566/177f540c-e1a9-47e6-bf1b-a2dc6cd28410">

**Comment by tischi** [comment]
@k-dominik can you try again?

**Comment by k-dominik** [comment]
I tried now also with a 3D image, and it seems to work. However I could not scroll through the volume. Are the shortcuts somehow different than the ones in bdv?

[export3d.zip](https://github.com/mobie/mobie-io/files/14618215/export3d.zip) <-- bat cochlea

**Comment by tischi** [comment]
> However I could not scroll through the volume. Are the shortcuts somehow different than the ones in bdv?

Nope, same short-cuts.

**Comment by tischi** [comment]
Bug on my side; I did not yet implement to check ilastik image dimensions. 
Will upload fix soon...have to go to gate now...

**Comment by tischi** [comment]
Should work now.
