### ISSUE TITLE
Repo naming

### ISSUE THREAD

**Issue by KateMoreva** [mobie/mobie-io#17]
Should we change the name or the repo as we have writers as well as imageloaders?

**Comment by constantinpape** [comment]
`bioimage-io` would be a good name. Does changing the repo name have consequences for pushing to sci-java.maven?
cc @ctrueden @imagejan

**Comment by tischi** [comment]
I think bioimage-io might be a bit too wide....
Maybe something with ngff?

**Comment by constantinpape** [comment]
> I think bioimage-io might be a bit too wide....

Sorry, I wanted to write `bigdataviewer-io` ... ([bioimage.io](https://bioimage.io/#/) is too hard-wired in my muscle memory right now :D)

**Comment by ctrueden** [comment]
Does changing the repo name have consequences for pushing to sci-java.maven?

Whatever groupId + artifactId you use, that's where it will be located on maven.scijava.org in the releases repository. But you can rename it to whatever you want, and the deploys will continue to function. Two things to consider, though:

1) If/when you start deploying to OSS Sonatype, their authentication mechanism is built around granting users access to specific groupIds, so if you then later change your groupId, you'd need to file a ticket. Before doing that, it is best practice to register a domain name aligned with your GitHub organization e.g. `mobie.sc` and then use the reverse domain (e.g. `sc.mobie`) for the groupId and ideally also Java package prefix.

2) If you change the groupId and/or artifactId, then the new Maven coordinate is considered a new artifact by Maven, meaning people could make a project depending on `old.group:old.artifact:1.0.0` and `new.group:new.artifact:2.0.0` in the same project—Maven does not treat `old.group:old.artifact` and `new.group:new.artifact` as the same thing at different versions, but rather two separate dependencies. And if there are class names appearing in both artifacts, it is likely to cause version skew.

So in general, my advice is: change the groupId/artifactId only when: A) you need to better conform to best practices (e.g. for OSS Sonatype deployment); or B) you are really forking the code into a new incarnation of the project with different package prefix.

**Comment by constantinpape** [comment]
Thanks for the detailed answer, @ctrueden!

> * If/when you start deploying to OSS Sonatype, their authentication mechanism is built around granting users access to specific groupIds, so if you then later change your groupId, you'd need to file a ticket. Before doing that, it is best practice to register a domain name aligned with your GitHub organization e.g. `mobie.sc` and then use the reverse domain (e.g. `sc.mobie`) for the groupId and ideally also Java package prefix.

Ok, having the `mobie.sc` org and using the reverse domain sounds like good practice  in any case.

> 
> * If you change the groupId and/or artifactId, then the new Maven coordinate is considered a new artifact by Maven, meaning people could make a project depending on `old.group:old.artifact:1.0.0` and `new.group:new.artifact:2.0.0` in the same project—Maven does not treat `old.group:old.artifact` and `new.group:new.artifact` as the same thing at different versions, but rather two separate dependencies. And if there are class names appearing in both artifacts, it is likely to cause version skew.

I think for now we are the only ones depending on this package; but if we decide to change the repo name and want to advertise this package for wider use, it would be better to have the same maven package and repo name in order to avoid confusion.

Anyway, most of us are on vacations for the rest of August,we will think about this afterwards.

**Comment by constantinpape** [comment]
I think we are happy with mobie-io for now.
