### ISSUE TITLE
Class names

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#32]
@KateMoreva @constantinpape 
I am confused about the names of those two classes:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/2157566/135446727-d8efb101-5479-473c-859c-d820d027a305.png">
Is one of them reading from the file system?
And is only one of them reading OME?

**Comment by KateMoreva** [comment]
They both are reading OME.
Renamed in `develop`.

**Comment by tischi** [comment]
OK, good point, I was looking at the master branch, but I guess I should have looked at the develop branch.
