### ISSUE TITLE
Unused code?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#33]
@K-Meech @KateMoreva Are we using this class at all?
```
public class N5ZarrWriter extends N5ZarrReader implements N5Writer
```

**Comment by K-Meech** [comment]
I don't think so. The ```N5OmeZarrWriter``` is basically a copy of this class, with minor changes to make it fit the OME spec. So I think the ```N5ZarrWriter``` is a direct copy of the saalfeld lab one: https://github.com/saalfeldlab/n5-zarr/blob/master/src/main/java/org/janelia/saalfeldlab/n5/zarr/N5ZarrWriter.java

**Comment by tischi** [comment]
If we don't use it, we could probably remove it, is it?

**Comment by KateMoreva** [comment]
> If we don't use it, we could probably remove it, is it?

It was removed in `develop.`
