### ISSUE TITLE
Add SpimDataOpener

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#47]
@KateMoreva @constantinpape 

- [x] Copy `SpimDataOpener` here
- [x] Copy `ImageDataFormats` here
- [x] Copy what we need from imagej-utils here
- [x] Add documentation (javaDoc) to the `ImageDataFormat` enum to make clear what each of the file formats is
- [ ] Test using those classes from mobie-viewer-fiji
- [ ] Delete those classes from mobie-viewer-fiji and depend on mobie-io instead
- [ ] Ping Tobias Pietzsch about `SpimDataOpener` as he was interested in either using our code or re-implementing something similar.

**Comment by constantinpape** [comment]
I think most of this is done already, @tischi could you check if any of the points here still need to be done and if yes say so /  otherwise close the issue.
