### ISSUE TITLE
v4 and BDV XML

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#68]
@constantinpape @K-Meech 

When we save data in `v0.4`, do we then still need the BDV XML?

**Comment by K-Meech** [comment]
I don't think so? As the scaling/transforms metadata is now supported? We should probably drop bdv ome-zarr from the project creator, and only support v0.4 ome-zarr then.

**Comment by tischi** [comment]
Yes, but would we need a script/function that converts data saved already as bdv.ome.zarr to pure ome.zarr? Otherwise I guess it would be difficult to edit old projects, would it?
Or maybe for the "edit" option it would still support the older formats for both read and write?

**Comment by K-Meech** [comment]
True - these old projects could still be opened in MoBIE, but it would be hard to edit them in the project creator. I don't think it would be too hard to make a script that would convert these bdv ome-zarr to v0.4 ome-zarr though. As far as I understand, only the metadata is different, not the actual chunks, so we would only need to re-write a few files...

**Comment by constantinpape** [comment]
> As the scaling/transforms metadata is now supported?

Just fyi, for now v0.4 only supports `scale` and `translation`; general affines will follow in the next release.
So if you want to keep support for affines we would need to stick to supporting the xml.

**Comment by K-Meech** [comment]
Good point. Ok - let's keep the bdv xml for now, and remove it once everything is supported.

**Comment by K-Meech** [comment]
Ok - started working on this, and I've changed my mind. Since, in MoBIE, we just have the scaling in the xml, and all affines handled by the views - then perhaps already we can remove the xml? This would make it simpler on the writing side, as otherwise we will have the xml + v0.4 ome-zarr, so potentially two conflicting sets of metadata on the transforms..

**Comment by constantinpape** [comment]
> . Since, in MoBIE, we just have the scaling in the xml, and all affines handled by the views - then perhaps already we can remove the xml? This would make it simpler on the writing side, as otherwise we will have the xml + v0.4 ome-zarr, so potentially two conflicting sets of metadata on the transforms..

Sounds good. I wasn't sure how well we actually enforce "just scaling in the xml", but that's probably a good opportunity to be strict about this.

**Comment by K-Meech** [comment]
I'll close this, as we decided to remove the xml for writing
