### ISSUE TITLE
Branch with minimal dependencies

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#7]
@KateMoreva @constantinpape 

I think one option would be to have a repository that does nothing else but open the data set as a `SpimData` object. 

Then one can do: `BdvFunctions.show( spimData )`; and could at least look at the data.

This would not have any nice rendering for the label masks, but it would have minimal dependencies. 

Maybe we could make a branch along those lines to see how that would work. The point would then also be to strip down the `pom.xml` to only contain what's really needed.

**Comment by constantinpape** [comment]
Yes, as discussed in the gathertown meeting I also think that's what we should do.
So we don't include the coloring model here (#2, #3) and also don't include fiji menus (#4) and just implement ome.zarr->spimdata with minimal dependencies here.

**Comment by constantinpape** [comment]
In particular, the changes fromhttps://github.com/mobie/mobie-viewer-fiji/pull/297 should also be moved in here and once the zarr support here is working, we switch MoBIE to depend on this repository.

**Comment by constantinpape** [comment]
This issue is outdated and just describes the `mobie-io` repo :).
