### ISSUE TITLE
Only write supported unit names, especially avoid non UTF-8 characters

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-io#74]
It would be good to only write unit names that are recommended in the v0.4 spec, see https://github.com/ome/ngff/blob/main/0.4/index.bs#L228-L229.

I understand that this is a bit tricky, since the unit names are read from the image metadata in Fiji, but we can add a dict with common translations and then throw a warning if no match is found.

It would be especially important to write `micrometer` instead of `$\mu$m`, to stick with simple string encoding; this otherwise might break implementations that only support utf-8.

(There might be an issue on this topic already, but I couldn't find it.)

**Comment by K-Meech** [comment]
I'll look into this - link this issue: https://github.com/mobie/mobie-viewer-fiji/issues/583
How do you handle this in the python library? Do you only accept the specific 0.4 strings? Also, do you specify a certain unit to use for the whole project? At the moment, I don't constrain this at all, so the project could be all in nanometer, all in micrometer etc...

**Comment by constantinpape** [comment]
I think this is implemented already, correct @K-Meech?

**Comment by K-Meech** [comment]
Yes - this is done already. If possible, it converts the unit to one of the approved OME-ZARR units.
