### ISSUE TITLE
Example files for different ome-zarr versions

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-io#8]
We aim to support the three different ome-zarr versions currently out there:
- 0.1 (this was the version used in the initial code), example data:
    -  https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr
- 0.2 (use nested hierarchy instead of flat hierarchy), example data:
    - https://s3.embassy.ebi.ac.uk/idr/zarr/v0.2/6001247.zarr
 - 0.3 (allow variable num of dimensions and introduce `axes` field in `multiscales`), example data:
     - `https://s3.embl.de/i2k-2020/ngff-example-data/v0.3` (with different files for different axes)
     
On the implementation side, the question is how to handle support for the different versions.
For now, I would suggest we just read the "version" from "multiscales:version" and have conditionals that handle the data correctly in the same class; we can refactor this to a cleaner solution later.

@joshmoore: do you have a link to example data for 0.2?

**Comment by joshmoore** [comment]
Hi @constantinpape, thanks for the reminder. I've just uploaded

https://s3.embassy.ebi.ac.uk/idr/zarr/v0.2/6001247.zarr

and will keep uploading more over the course of the next week.

**Comment by constantinpape** [comment]
Thanks @joshmoore!

**Comment by KateMoreva** [comment]
The reader [(version)](https://github.com/mobie/bigdataviewer-ome-zarr/pull/9) can open ome-zarr files of versions 0.1, 0.2 and 0.3 only if files are 3-5D.
