### ISSUE TITLE
OME-Zarr SpimData platy-raw loaded twice

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#88]
@constantinpape @KateMoreva 

Not sure whether it is a bug in the code or in the file, but the data is loaded twice:

`https://s3.embl.de/i2k-2020/platy-raw.ome.zarr`

<img width="634" alt="image" src="https://user-images.githubusercontent.com/2157566/159691894-c7caadfc-ac45-4898-abc8-ee8c5a6465f1.png">

**Comment by constantinpape** [comment]
This is a minor issue with the data, I will fix it.
