### ISSUE TITLE
Rename FileAndURIUtils?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#92]
Suggestions:

- IOUtils

Other ideas?

@constantinpape @K-Meech @KateMoreva

**Comment by K-Meech** [comment]
```IOUtils``` sounds good to me.

**Comment by tischi** [comment]
Or maybe `IOHelper` to be consistent with mobie-viewer-fiji?

I have no strong opinion, I'd leave this up to @KateMoreva...

**Comment by constantinpape** [comment]
Both `IOHelper` or `IOutils` sound good to me.
